### ISSUE TITLE
Categories Card

### ISSUE THREAD

**Issue by rrusher** [hlxsites/walgreens#18]
Create a block that uses [this API](https://www.walgreens.com/catalogsearch/v1/categories?ids=359434,359436,359441,359438) to populate the cards.

<img width="822" alt="Screenshot 2023-09-11 at 5 52 29 PM" src="https://github.com/hlxsites/walgreens/assets/6796243/bf7e64d4-3c54-47f5-a980-023ebdce3926">

**Comment by mtemk** [comment]
Current changes can be found in the categories block js and css files.
